### PR TITLE
Filters Should Be Able To Exclude Test Projects

### PR DESCRIPTION
**Pull request by cnwilkin**
Started working on this and figured I'd make it visible to others.

ToDo:
- [x] Integrate new Filter object with Giles
- [x] Integrate new Filter object with test runners
- [x] Integrate new Filter object with user input handler

### CODE REVIEW

**Comment by cnwilkin** [comment]
Currently this code doesn't even compile because I'm struggling to figure out how the last two items on the checklist work.

**Comment by cnwilkin** [comment]
After many iterations and stumbling on my part I finally came up with a working design. So take a look and let me know what I should do to improve.

**Comment by codereflection** [comment]
Awesome, thanks Chad! I'll take a look.

**Comment by codereflection** [comment]
Looks good to me, merged into master. I just need to push out a new package to Nuget now.

Thanks again Chad!

**Comment by cnwilkin** [comment]
No problem. Thanks for a great project!

**Comment by codereflection** [comment]
Hey Chad, I have 5 failing tests after merging this into master. Are you seeing that as well?

**Comment by cnwilkin** [comment]
Yes I saw that but to be honest I didn't give them much thought. I figured they where supposed to fail like the NUnit tests.  I've never used mspec before but I'll install the resharper plugin and report back what I find.

**Comment by cnwilkin** [comment]
Am I missing something obvious when trying to run these mspec tests. I installed the resharper plugin but when I run the tests the mspec one's are detected but never ran.

**Pull request merged**
