### PR TITLE
Support solution path which is simply a filename.

### PR DESCRIPTION
**Pull request by mpareja**
Fixes launching like so: Giles -s MySolution.sln -t (...)

### CODE REVIEW

**Comment by codereflection** [comment]
Hey Mario! Can you see if this works with the latest bits?

**Comment by mpareja** [comment]
I'll try and check this out later tonight.

**Comment by mpareja** [comment]
I've merged all your recent changes from master into this branch and verified it still works as expected.

Here are the steps to reproduce the original bug:

```
cd <projects dir>\Giles\src
..\build\Giles.exe -s Giles.sln
```

Unhandled Exception: System.ArgumentException: The directory name  is invalid.

**Comment by codereflection** [comment]
Damn, looks like recent changes have broken the ability to auto merge this, sorry!! :(

**Comment by mpareja** [comment]
I'll try to update branch later tonight.

**Pull request closed without merging**
