### PR TITLE
Adding init script to copy giles executor to the solution dir on install.

### PR DESCRIPTION
**Pull request by idavis**
Now users can just do

install-package giles
.\giles

and it is up and running.

### CODE REVIEW

**Comment by NotMyself** [comment]
that is so freaking hawt! ill look into doing a video this weekend..

Im thinking track two from this album for a sound track...
http://kleptones.com/pages/downloads_fd2ja.html

On Thu, Sep 1, 2011 at 12:43 PM, idavis <
reply@reply.github.com>wrote:

> Now users can just do
> 
> install-package giles
> .\giles
> 
> and it is up and running.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/codereflection/Giles/pull/9

## 

"The explanation requiring the fewest assumptions is most likely to be
correct."
- Occams Razor
  http://en.wikipedia.org/wiki/Occam's_Razor

**Comment by idavis** [comment]
When working on giles, you can also now use

.\giles.ps1 src\giles.sln

and giles will run itself - just beware of builds trying to run.

**Comment by NotMyself** [comment]
its funny because Jeff and I were talking about this at lunch today. Specifically about the nuget install experience.

**Comment by codereflection** [comment]
Awesome. Yeah, I brought it up because Ian had the idea earlier today. :)

Looks good, I'm pullin it in.

**Pull request merged**
